name: Frontend Production
on:
  push:
    branches: [main]

jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: make install-dependencies lint

  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '--no-deploy') }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          git config --global user.name 'Sergei Melodyn'
          git config --global user.email 'samelodyn@gmail.com'
          git remote add gh-token "https://${{secrets.GH_TOKEN}}@github.com/:user/:repo.git"
          git checkout --orphan gh-pages
          git merge main
      - run: |
          make ci-build
          cp -r ./dist/* ./
          rm -rf ./dist
          git add .
          git commit -am "Release"
          git push gh-token gh-pages
